/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synacor_txid_Txid120Factory */

#ifndef _Included_com_synacor_txid_Txid120Factory
#define _Included_com_synacor_txid_Txid120Factory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synacor_txid_Txid120Factory
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synacor_txid_Txid120Factory_init
  (JNIEnv *, jclass);

/*
 * Class:     com_synacor_txid_Txid120Factory
 * Method:    getTxid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synacor_txid_Txid120Factory_getTxid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
