/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synacor_jetty_log_txid_Txid120Source */

#ifndef _Included_com_synacor_jetty_log_txid_Txid120Source
#define _Included_com_synacor_jetty_log_txid_Txid120Source
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synacor_jetty_log_txid_Txid120Source
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synacor_jetty_log_txid_Txid120Source_init
  (JNIEnv *, jclass);

/*
 * Class:     com_synacor_jetty_log_txid_Txid120Source
 * Method:    getTxid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synacor_jetty_log_txid_Txid120Source_getTxid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
