/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synacor_jetty_log_Txid */

#ifndef _Included_com_synacor_jetty_log_Txid
#define _Included_com_synacor_jetty_log_Txid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synacor_jetty_log_Txid
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synacor_jetty_log_Txid_init
  (JNIEnv *, jclass);

/*
 * Class:     com_synacor_jetty_log_Txid
 * Method:    getTxid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synacor_jetty_log_Txid_getTxid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
